name: 'Build LaTex Document'
on: 
  push:
jobs:
  build-resume-ptbr:
    runs-on: ubuntu-latest
    steps:
      - name: Install libfuse2 # needed for AppImage
        run: |
          sudo add-apt-repository universe
          sudo apt install libfuse2
      - name: Checkout
        uses: actions/checkout@v3
      - uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tectonic
        run: cd resume-ptbr && tectonic -X build
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: main.pdf

  build-resume-en:
    runs-on: ubuntu-latest
    steps:
      - name: Install libfuse2 # needed for AppImage
        run: |
          sudo add-apt-repository universe
          sudo apt install libfuse2
      - name: Checkout
        uses: actions/checkout@v3
      - uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tectonic
        run: cd resume-en && tectonic -X build
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: main.pdf